# Generated by Django 5.0.7 on 2025-05-28 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10, null=True)),
                ('tu_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=300, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('peso_actual', models.CharField(blank=True, max_length=300, null=True)),
                ('altura', models.CharField(blank=True, max_length=300, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=300, null=True)),
                ('alergias', models.CharField(blank=True, max_length=300, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=300, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=300, null=True)),
                ('lesiones', models.CharField(blank=True, max_length=300, null=True)),
                ('tiempo_lesiones', models.CharField(blank=True, max_length=100, null=True)),
                ('hijos', models.CharField(blank=True, max_length=300, null=True)),
                ('rutina_diaria', models.TextField(blank=True, null=True)),
                ('meta_personal', models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=30, null=True)),
                ('interesado_dieta', models.BooleanField(default=False)),
                ('interesado_entrenamiento', models.BooleanField(default=False)),
                ('interesado_farmacologia', models.BooleanField(default=False)),
                ('desea_atencion_personalizada', models.BooleanField(default=False)),
                ('uso_farmacologia', models.CharField(blank=True, max_length=300, null=True)),
                ('uso_suplementos', models.CharField(blank=True, max_length=300, null=True)),
                ('ha_competido', models.BooleanField(default=False)),
                ('numero_competiciones', models.CharField(blank=True, max_length=300, null=True)),
                ('dias_regla', models.CharField(blank=True, help_text='Solo aplica si eres mujer', max_length=300, null=True)),
                ('irregular_promedio_3_meses', models.CharField(blank=True, help_text='Solo aplica si eres mujer', max_length=300, null=True)),
                ('esta_embarazada', models.BooleanField(default=False, help_text='Solo aplica si eres mujer')),
                ('meses_embarazo', models.CharField(blank=True, max_length=300, null=True)),
                ('tiempo_postparto', models.CharField(blank=True, max_length=100, null=True)),
                ('ha_abortado', models.BooleanField(default=False)),
                ('tipo_aborto', models.CharField(blank=True, choices=[('natural', 'Natural'), ('inducido', 'Inducido')], max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
