# Generated by Django 5.0.7 on 2025-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuestrosAtletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.CharField(blank=True, max_length=100, null=True)),
                ('titulos_competitivos', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas')),
            ],
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='rutina_diaria',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
