# Generated by Django 5.0.7 on 2025-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0002_nuestrosatletas_alter_registrousuario_rutina_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuestrosatletas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
