# Generated by Django 5.0.7 on 2025-05-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_nuestrosatletas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuestrosatletas',
            name='paid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
