# Generated by Django 5.0.7 on 2025-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_remove_nuestrosatletas_paid_nuestrosatletas_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_personal', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='dietas/')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_personal', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='rutinas/')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('rutina_basica', 'Rutina Básica'), ('dieta_basica', 'Dieta Básica'), ('completo_basico', 'Completo Básico (Dieta + Rutina)'), ('rutina_premium', 'Rutina Premium'), ('dieta_premium', 'Dieta Premium'), ('completo_premium', 'Completo Premium (Dieta + Rutina)')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personalizado', models.BooleanField(default=False)),
            ],
        ),
    ]
