# Generated by Django 5.0.7 on 2025-05-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_paquete_stripe_price_id_accesousuariopaquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidodieta',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to='fitapp.paquete'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='fitapp.paquete'),
        ),
    ]
