# Generated by Django 5.0.7 on 2025-05-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_contenidodieta_paquete_contenidorutina_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_personal', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=30)),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10, null=True)),
                ('tipo_contenido', models.CharField(choices=[('dieta', 'Dieta'), ('rutina', 'Rutina')], max_length=10)),
                ('contenido', models.TextField()),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='fitapp.paquete')),
            ],
        ),
    ]
