# Generated by Django 5.0.7 on 2025-05-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0009_contenidopaquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenidoPaquete',
        ),
    ]
