# Generated by Django 5.0.7 on 2025-05-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_paquete_titulo_alter_paquete_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='nombre',
            new_name='categoria',
        ),
    ]
