# Generated by Django 5.0.7 on 2025-05-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0012_rename_nombre_paquete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/paquetes'),
        ),
    ]
