# Generated by Django 5.0.7 on 2025-05-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0013_paquete_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='meta_personal',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=100, null=True),
        ),
    ]
