# Generated by Django 5.0.7 on 2025-05-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0014_paquete_meta_personal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fitapp.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'paquete')},
            },
        ),
    ]
