# Generated by Django 5.0.7 on 2025-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0015_comprapaquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprapaquete',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
