# Generated by Django 5.0.7 on 2025-05-31 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0016_comprapaquete_stripe_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprapaquete',
            options={'verbose_name': 'Paquetes Vendidos', 'verbose_name_plural': 'Paquetes Vendidos'},
        ),
        migrations.RemoveField(
            model_name='contenidodieta',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='contenidodieta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contenidorutina',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='contenidorutina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='personalizado',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='stripe_price_id',
        ),
        migrations.CreateModel(
            name='SemanaDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.PositiveSmallIntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4')])),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='fitapp.contenidodieta')),
            ],
        ),
        migrations.CreateModel(
            name='DietaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('desayuno', models.TextField()),
                ('desayuno_hora', models.TimeField()),
                ('snack1', models.TextField(blank=True, null=True)),
                ('snack_hora1', models.TimeField(blank=True, null=True)),
                ('almuerzo', models.TextField()),
                ('almuerzo_hora', models.TimeField()),
                ('snack2', models.TextField(blank=True, null=True)),
                ('snack_hora2', models.TimeField(blank=True, null=True)),
                ('cena', models.TextField()),
                ('cena_hora', models.TimeField()),
                ('snack', models.TextField(blank=True, null=True)),
                ('snack_hora', models.TimeField(blank=True, null=True)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='fitapp.semanadieta')),
            ],
            options={
                'unique_together': {('semana', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='SemanaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.PositiveSmallIntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4')])),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='fitapp.contenidorutina')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('entrenamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_ejercicio', models.PositiveSmallIntegerField(choices=[(1, 'Ejercicio 1'), (2, 'Ejercicio 2'), (3, 'Ejercicio 3'), (4, 'Ejercicio 4'), (5, 'Ejercicio 5'), (6, 'Ejercicio 6'), (7, 'Ejercicio 7'), (8, 'Ejercicio 8')])),
                ('descripcion_ejercicio', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube (opcional)', null=True)),
                ('duracion_aproximada', models.DurationField()),
                ('descripcion', models.TextField()),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='fitapp.semanarutina')),
            ],
            options={
                'unique_together': {('semana', 'dia', 'numero_ejercicio')},
            },
        ),
        migrations.DeleteModel(
            name='AccesoUsuarioPaquete',
        ),
    ]
