# Generated by Django 5.0.7 on 2025-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0017_alter_comprapaquete_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rutinadia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rutinadia',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='semanadieta',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='semanarutina',
            name='rutina',
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='dietas/'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='rutinas/'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenidodieta',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contenidorutina',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DietaDia',
        ),
        migrations.DeleteModel(
            name='RutinaDia',
        ),
        migrations.DeleteModel(
            name='SemanaDieta',
        ),
        migrations.DeleteModel(
            name='SemanaRutina',
        ),
    ]
