# Generated by Django 5.0.7 on 2025-06-01 15:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0018_alter_rutinadia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidodieta',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='contenidorutina',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='contenidodieta',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='contenidorutina',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Contenido'),
        ),
    ]
