# Generated by Django 5.0.7 on 2025-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0019_remove_contenidodieta_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
    ]
