# Generated by Django 5.0.7 on 2025-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0020_paquete_es_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidodieta',
            name='meta_personal',
        ),
        migrations.RemoveField(
            model_name='contenidorutina',
            name='meta_personal',
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image23',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image24',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='semana1',
            field=models.CharField(default='SEMANA 1', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='semana2',
            field=models.CharField(default='SEMANA 2', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='semana3',
            field=models.CharField(default='SEMANA 3', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidodieta',
            name='semana4',
            field=models.CharField(default='SEMANA 4', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image23',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image24',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='images/nuestros_atletas'),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='semana1',
            field=models.CharField(default='SEMANA 1', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='semana2',
            field=models.CharField(default='SEMANA 2', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='semana3',
            field=models.CharField(default='SEMANA 3', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidorutina',
            name='semana4',
            field=models.CharField(default='SEMANA 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='categoria',
            field=models.CharField(choices=[('rutina_basica', 'Rutina Básica'), ('dieta_basica', 'Dieta Básica'), ('completo_basico', 'Completo Básico (Dieta + Rutina)'), ('rutina_premium', 'Rutina Premium'), ('dieta_premium', 'Dieta Premium'), ('completo_premium', 'Completo Premium (Dieta + Rutina)'), ('farmacologia', 'Farmacologia')], max_length=50, verbose_name='Categoria de Paquete'),
        ),
    ]
