# Generated by Django 5.0.7 on 2025-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0021_remove_contenidodieta_meta_personal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuplementosYFarmacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_personal', models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad')], max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_de_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_de_vencimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
