# Generated by Django 5.0.7 on 2025-06-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0023_direcciondeenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciondeenvio',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='meta_personal',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad'), ('otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='meta_personal',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='suplementosyfarmacos',
            name='meta_personal',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad'), ('otro', 'Otro')], max_length=100, null=True),
        ),
    ]
