# Generated by Django 5.0.7 on 2025-06-10 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0024_direcciondeenvio_pagado_alter_paquete_meta_personal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraSuplementoFarmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.direcciondeenvio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.suplementosyfarmacos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
