# Generated by Django 5.0.7 on 2025-06-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0025_comprasuplementofarmaco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='pagado',
        ),
    ]
