# Generated by Django 5.0.7 on 2025-06-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0027_comprasuplementofarmaco_tipo_de_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasuplementofarmaco',
            options={'verbose_name': 'Suplementos y Fármacos Vendidos', 'verbose_name_plural': 'Suplementos y Fármacos Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='suplementosyfarmacos',
            options={'verbose_name': 'Lista de Suplementos y Fármacos en tienda', 'verbose_name_plural': 'Lista deSuplementos y Fármacos en tienda'},
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.suplementosyfarmacos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
