# Generated by Django 5.0.7 on 2025-06-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0029_alter_comprasuplementofarmaco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suplementosyfarmacos',
            options={'verbose_name': 'Lista de Suplementos y Fármacos en tienda', 'verbose_name_plural': 'Lista de Suplementos y Fármacos en tienda'},
        ),
        migrations.RemoveField(
            model_name='comprasuplementofarmaco',
            name='envio_realizado',
        ),
    ]
