# Generated by Django 5.0.7 on 2025-06-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0030_alter_suplementosyfarmacos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='envio_realizado',
        ),
        migrations.AddField(
            model_name='comprasuplementofarmaco',
            name='envio_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
