# Generated by Django 5.0.7 on 2025-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0031_remove_direcciondeenvio_envio_realizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasuplementofarmaco',
            options={'verbose_name': 'Lista de Productos Vendidos', 'verbose_name_plural': 'Lista de Productos Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='suplementosyfarmacos',
            options={'verbose_name': 'Lista de Productos en tienda', 'verbose_name_plural': 'Lista de Productos en tienda'},
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='opcion_entrega',
            field=models.CharField(default='', help_text='Ej: ¿Retiro en sucursal o prefieres entrega en casa?', max_length=100),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='direccion',
            field=models.TextField(help_text='Porfavor indica tu direccón Completa incluyendo numero Exterior e interior si Aplica'),
        ),
    ]
