# Generated by Django 5.0.7 on 2025-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0032_alter_comprasuplementofarmaco_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='tiene_envio_gratis',
            field=models.BooleanField(default=False, help_text='Marca si el producto no genera costo de envío.'),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='opcion_entrega',
            field=models.CharField(default='', max_length=100),
        ),
    ]
