# Generated by Django 5.0.7 on 2025-06-16 01:35

import django.db.models.deletion
import fitapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fitapp', '0033_suplementosyfarmacos_tiene_envio_gratis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ropa', 'Ropa'), ('calzado', 'Calzado')], max_length=100)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('tiene_envio_gratis', models.BooleanField(default=False)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='TallaCalzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=10)),
                ('us', models.DecimalField(decimal_places=1, max_digits=4)),
                ('eu', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cm', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TallaRopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='content_type',
            field=models.ForeignKey(default=fitapp.models.get_default_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suplementosyfarmacos',
            name='meta_personal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suplementosyfarmacos',
            name='tiene_envio_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('envio_realizado', models.BooleanField(default=False)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.direcciondeenvio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fitapp.compra')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=20)),
                ('color', models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rosado', 'Rosado'), ('morado', 'Morado'), ('naranja', 'Naranja'), ('marrón', 'Marrón'), ('beige', 'Beige'), ('multicolor', 'Multicolor')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='fitapp.producto')),
                ('talla_calzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitapp.tallacalzado')),
                ('talla_ropa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitapp.tallaropa')),
            ],
        ),
        migrations.DeleteModel(
            name='CompraSuplementoFarmaco',
        ),
    ]
