# Generated by Django 5.0.7 on 2025-06-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0034_producto_tallacalzado_tallaropa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_envio_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_envio_express_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_envio_express_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_envio_internacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_envio_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suplementosyfarmacos',
            name='meta_personal',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Pérdida de peso'), ('masa_muscular', 'Aumento de masa muscular'), ('definicion', 'Definición (definición muscular)'), ('estetica', 'Estética (masa muscular/definición muscular)'), ('rendimiento', 'Mejorar rendimiento físico'), ('fuerza', 'Fuerza'), ('competencia', 'Competencia'), ('potencia_sexual', 'Aumentar potencia sexual'), ('longevidad', 'Longevidad'), ('otro', 'Otro')], max_length=100, null=True),
        ),
    ]
