# Generated by Django 5.0.7 on 2025-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0035_varianteproducto_precio_envio_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suplementosyfarmacos',
            options={'verbose_name': 'Lista de Productos Generales', 'verbose_name_plural': 'Lista de Productos Generales'},
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_internacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
