# Generated by Django 5.0.7 on 2025-06-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0036_alter_suplementosyfarmacos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='laboratorio',
        ),
    ]
