# Generated by Django 5.0.7 on 2025-06-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0038_producto_foto10_producto_foto4_producto_foto5_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'verbose_name': 'Ropa y Calzado', 'verbose_name_plural': 'Ropa y Calzado'},
        ),
    ]
