# Generated by Django 5.0.7 on 2025-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0039_alter_varianteproducto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='precio_envio_domicilio',
        ),
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_domicilio',
        ),
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_sucursal',
        ),
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='precio_envio_internacional',
        ),
        migrations.RemoveField(
            model_name='suplementosyfarmacos',
            name='precio_envio_sucursal',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='precio_envio_domicilio',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='precio_envio_express_domicilio',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='precio_envio_express_sucursal',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='precio_envio_internacional',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='precio_envio_sucursal',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_envio_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_envio_express_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_envio_express_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_envio_internacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_envio_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
