# Generated by Django 5.0.7 on 2025-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0040_remove_suplementosyfarmacos_precio_envio_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Ropa y Calzado', 'verbose_name_plural': 'Ropa y Calzado'},
        ),
        migrations.AlterModelOptions(
            name='tallacalzado',
            options={'verbose_name': 'Tallas Calzado', 'verbose_name_plural': 'Tallas Calzado'},
        ),
        migrations.AlterModelOptions(
            name='tallaropa',
            options={'verbose_name': 'Tallas Ropa', 'verbose_name_plural': 'Tallas Ropa'},
        ),
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'verbose_name': 'Stock tallas ropa Calzado', 'verbose_name_plural': 'Stock tallas ropa Calzado'},
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_express_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_internacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suplementosyfarmacos',
            name='precio_envio_sucursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
