# Generated by Django 5.0.7 on 2025-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0041_alter_producto_options_alter_tallacalzado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
