# Generated by Django 5.0.7 on 2025-06-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0042_carritoitem_color_carritoitem_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.varianteproducto'),
        ),
    ]
