# Generated by Django 5.0.7 on 2025-06-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0043_carritoitem_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitapp.varianteproducto'),
        ),
    ]
