# Generated by Django 5.0.7 on 2025-06-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0044_alter_carritoitem_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciondeenvio',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
