# Generated by Django 5.0.7 on 2025-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0045_direcciondeenvio_costo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='opcion_entrega',
            field=models.CharField(choices=[('domicilio', 'Entrega a domicilio'), ('domicilio_express', 'Entrega a domicilio (Express)'), ('sucursal', 'Retiro en sucursal'), ('sucursal_express', 'Retiro en sucursal (Express)')], default='domicilio', max_length=100, verbose_name='¿Retiro en sucursal o prefieres entrega en casa?'),
        ),
    ]
