# Generated by Django 5.0.7 on 2025-06-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0046_alter_direcciondeenvio_opcion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitapp.varianteproducto'),
        ),
    ]
