# Generated by Django 5.0.7 on 2025-06-20 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0047_compraitem_variante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuestrosatletas',
            options={'verbose_name': 'Nuestros Atletas', 'verbose_name_plural': 'Nuestros Atletas'},
        ),
        migrations.AddField(
            model_name='paquete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='pais',
            field=models.CharField(default='México', max_length=100),
        ),
    ]
