# Generated by Django 5.0.7 on 2025-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0048_alter_nuestrosatletas_options_paquete_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='notas_de_envio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notas de Envio'),
        ),
    ]
