# Generated by Django 5.0.7 on 2025-06-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0049_compra_notas_de_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Productos Vendidos ', 'verbose_name_plural': 'Productos Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='direcciondeenvio',
            options={'verbose_name': 'Direcciones de Clientes', 'verbose_name_plural': 'Direcciones de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='paquete',
            options={'verbose_name': 'Lista de Paquetes en Tienda', 'verbose_name_plural': 'Lista de Paquetes en Tienda'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Lista de Ropa y Calzado en Tienda', 'verbose_name_plural': 'Lista de Ropa y Calzado en Tienda'},
        ),
        migrations.AlterModelOptions(
            name='suplementosyfarmacos',
            options={'verbose_name': 'Lista de Productos Generales en Tienda', 'verbose_name_plural': 'Lista de Productos Generales en Tienda'},
        ),
        migrations.AlterField(
            model_name='paquete',
            name='categoria',
            field=models.CharField(choices=[('rutina_basica', 'Rutina Básica'), ('dieta_basica', 'Dieta Básica'), ('completo_basico', 'Completo Básico (Dieta + Rutina)'), ('rutina_premium', 'Rutina Premium'), ('dieta_premium', 'Dieta Premium'), ('completo_premium', 'Completo Premium (Dieta + Rutina)'), ('completo_premium_con_farmacologia', 'Dieta + Rutina + Farmacologia')], max_length=50, verbose_name='Categoria de Paquete'),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tallaropa',
            name='codigo',
            field=models.CharField(help_text='Ej: S, M, L, XL', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
