# Generated by Django 5.0.7 on 2025-06-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0050_alter_compra_options_alter_direcciondeenvio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='lesiones',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrousuario',
            name='tiempo_lesiones',
            field=models.CharField(blank=True, help_text='tipo y tiempo de lecciones', max_length=100, null=True),
        ),
    ]
