# Generated by Django 5.0.7 on 2025-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0051_alter_direcciondeenvio_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprapaquete',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
