# Generated by Django 5.0.7 on 2025-06-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0053_remove_comprapaquete_entregado_paquete_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuario',
            name='tipo_de_lesiones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
