# Generated by Django 5.0.7 on 2025-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0054_registrousuario_tipo_de_lesiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='entregado',
        ),
        migrations.AddField(
            model_name='comprapaquete',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
