"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4(i1#^3o)eceftas3b8au(i0ii_9x0w#bg3i!)(y3k0xec9e%l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fitapp',
    'django_ckeditor_5',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



import os
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'
SITE_URL = 'https://www.belmontherrera.com'


# CKEditor 5 
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'undo', 'redo', '|',               # Deshacer / Rehacer y separador
            'heading', '|',                    # Encabezados y separador
            'bold', 'italic', 'underline', 'strikethrough', '|',  # Estilos de texto y separador
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',  # Tamaño y colores de texto y fondo, separador
            'link', 'blockQuote', '|',         # Insertar enlace, cita y separador
            'bulletedList', 'numberedList', '|',  # Listas con viñetas y numeradas, separador
            'alignment', 'insertTable', '|',   # Alineación y opción de insertar tabla, separador
            'highlight'                        # Resaltado de texto
        ],
        'height': 500,                        # Altura del editor en píxeles
        'width': '100%',                      # Ancho del editor (100% del contenedor)
        'toolbarCanCollapse': False,          # No permitir colapsar la barra de herramientas
        'fontSize': {
            'options': [
                'tiny',
                'small',
                'default',
                'big',
                'huge'
            ],
            'supportAllValues': False
        },
        'table': {
            'contentToolbar': [
                'tableColumn',                # Herramienta para insertar columnas en la tabla
                'tableRow',                   # Herramienta para insertar filas en la tabla
                'mergeTableCells',            # Herramienta para unir celdas de tabla
                'tableProperties',            # Propiedades generales de la tabla
                'tableCellProperties'         # Propiedades de celdas individuales
            ],
            'resizeUnit': 'px',               # Unidad para cambiar el tamaño de la tabla (píxeles)
            'resizeTable': True               # Habilitar redimensionamiento manual de la tabla
        }
    }
}














REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}




# Claves de API de Stripe
# settings.py (NO USAR EN PRODUCCIÓN)
STRIPE_PUBLISHABLE_KEY = "pk_test_51PMxD3D4NKq6bhdMwnGjQqKZ1MvYgoSTCAgmB6F3VBkTa3wlaFajTCxZ55FETSXB2DmFYWFX0VDRtB8nRToIVnz300rHytQdUq"
STRIPE_SECRET_KEY = "sk_test_51PMxD3D4NKq6bhdMxg4Kwd9MuRVZcddXpkO1GiKEwkFPHXk7NyzXdQQGnaJWzO8RpNuuyQuqC6MMnschbJcKIl7600oGwUW0Z0"


STRIPE_CURRENCY = "mxn"

SESSION_COOKIE_SAMESITE = 'Lax' #ESTO LO AGREGUE PARA PODER HACER LOS PAGOS PORQUE ME ESTABA REDIRECCIONANDO AL PAGO DDE NUEVO

import logging
logger = logging.getLogger('django.mail')
logger.setLevel(logging.DEBUG)

# CONFIGURACION PARA ENVIAR EMAILS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'proyectodigitalmexico@gmail.com'
EMAIL_HOST_PASSWORD = 'fjda ypvm egqk gele'
DEFAULT_FROM_EMAIL = 'proyectodigitalmexico@gmail.com'
# Email configuration
DEFAULT_FROM_EMAIL = 'proyectodigitalmexico@gmail.com'
APPOINTMENT_EMAIL = 'proyectodigitalmexico@gmail.com'



DOMAIN = "http://localhost:8000" # ESTO LO AGREGUE PARA PODER QUE SE ENVIE LA FOTO EN EL EMAIL DE CONFIRMACION