labels = {
    'genero': 'Género',
    'user': 'Usuario',
    'tu_nombre': 'Nombre',
    'last_name': 'Apellidos',
    'email': 'Correo Electrónico',
    'foto_perfil': 'Foto de perfil',
    'fecha_nacimiento': 'Fecha de nacimiento',
    'estado_civil': 'Estado civil',
    'numero_telefono': 'Número de teléfono',
    'contacto_emergencia': 'Contacto de emergencia',

    'peso_actual': 'Peso actual',
    'altura': 'Altura',
    'enfermedades': 'Enfermedades',
    'alergias': 'Alergias',
    'medicamentos': 'Medicamentos',
    'cirugias': 'Cirugías',
    'lesiones': 'Lesiones',
    'tipo_de_lesiones':'Si marcaste que tienes lesiones espeicicifa que tipo',
    'tiempo_lesiones': 'Tiempo con lesiones',

    'hijos': 'Número de hijos',
    'rutina_diaria': 'Rutina diaria',

    'meta_personal': 'Meta personal',
    'interesado_dieta': 'Interesado en dieta',
    'interesado_entrenamiento': 'Interesado en entrenamiento',
    'interesado_farmacologia': 'Interesado en farmacología',
    'desea_atencion_personalizada': 'Desea atención personalizada',

    'uso_farmacologia': 'Uso de farmacología',
    'uso_suplementos': 'Uso de suplementos',
    'ha_competido': '¿Ha competido?',
    'numero_competiciones': 'Número de competiciones',

    'dias_regla': 'Días de regla',
    'irregular_promedio_3_meses': 'Irregularidad promedio en 3 meses',
    'esta_embarazada': '¿Está embarazada?',
    'meses_embarazo': 'Meses de embarazo',
    'tiempo_postparto': 'Tiempo postparto',
    'ha_abortado': '¿Ha abortado?',
    'tipo_aborto': 'Tipo de aborto',
}


# Placeholders personalizados para campos importantes
placeholders = {
    'tu_nombre': 'Ingresa tu nombre completo',
    'last_name': 'Ingresa tus apellidos',
    'email': 'ejemplo@correo.com',
    'fecha_nacimiento': 'DD/MM/AAAA',
    'numero_telefono': 'Ej. +52 1234567890',
    'contacto_emergencia': 'Teléfono de emergencia',
    'peso_actual': 'Ej. 65 kg',
    'altura': 'Ej. 1.70 m',
    'enfermedades': 'Enfermedades relevantes (si aplica)',
    'alergias': 'Alergias (si aplica)',
    'medicamentos': 'Medicamentos actuales',
    'cirugias': 'Tipo y fecha de cirugía',
    'tipo_de_lesiones': 'Describe tus lesiones',
    'tiempo_lesiones': 'Ej. 2 meses',
    'meta_personal': 'Selecciona tu meta principal',
    'uso_farmacologia': '¿Qué fármacos usas y con qué frecuencia?',
    'uso_suplementos': '¿Qué suplementos estás usando?',
    'numero_competiciones': 'Ej. 2 competencias',
    'dias_regla': 'Promedio de duración',
    'irregular_promedio_3_meses': 'Describe tu ciclo menstrual',
    'meses_embarazo': 'Número de meses de embarazo',
    'tiempo_postparto': 'Ej. 3 meses',
}
